sudo: required
language: node_js #node, python
git:
  depth: 2
  autocrlf: input
  branches:
    only:
      - master
services:
  - docker
before_install:
  - echo "이미지 생성 성공"
  - docker build -t ejayjeon/react -f dockerfile.dev .
script:
  - docker run -e CI=true ejayjeon/react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "react"
  env: "docker-react-env"
  bucket_name: ""
  buckey_path: "react"
  on:
    branch: master #master에 소스코드가 올라올 때에만 AWS에 배포
  access_key_id: $AWS_ACCESS_KEY
  access_secret_key: $AWS_SECRET_ACCESS_KEY
after_success:
  - echo "테스트 성공"
