# builder stage
FROM node:16 as builder
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY ./ ./
CMD [ "npm", "run", "build" ]

# run stage
FROM nginx 
# 기본포트 80
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
# builder로부터 가져와서 -> 실제 nginx가 사용할 폴더에다가 복사해서 넣는 것