FROM node:16
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY ./ ./
CMD ["npm", "run", "start"]

# dockerfile.dev의 경우 바로 docker build : 파일을 못찾음

# docker build -f dockerfile.dev ./
# 이미지를 빌드할 때 쓰일 도커 파일을 임의로 참조하여 지정해주는 방법
# 도커환경에서 react환경을 실행할 때에는 굳이 로컬에 node_modules가 필요하지 않아 -> 빌드시간이 더 길어짐 -> 지워줘도 됨
#docker run -it -dp 3000:3000 ejayjeon/react

# COPY 대신 Volume
# Volumn : 호스트 폴더를 참조한다. 그렇지만 호스트 폴더에서 node_modules를 지워줬기 때문에 node_modules는 참조하지 말라는 의미 -v usr/src/app/node_modules, 그 외에 현재 강로에 있는 것들을 참조하라


# docker run -it -p 3000:3000 -v /usr/src/app/node_modules -v ${pwd}:/usr/src/app ejayjeon/react 
# (pwd) : 경로를 못찾았다고 안됨
# pwd뒤에 경로를 지움 : 경로를 입력하라고 함