FROM --platform=arm64 node:16 as builder 
WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY ./ ./
RUN npm run build

FROM nginx
EXPOSE 3000
#Nginx를 가동하고 윗 단계에서 생성된 빌드 파일을 제공, default.conf에서 해준 설정을 nginx 컨테이너 안에 있는 설정이 되게 복사를 해줌

# 정적 파일 제공을 위해 fe 안에 nginx 폴더를 생성하고, default.conf 파일을 생성
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html