FROM node:10

# 이미지 안에서 어플리케이션 소스를 가지고 있을 디렉토리
WORKDIR /usr/src/app

# 모듈을 계속 받지 않고 Caching 기능을 이용하기 위해서
COPY package.json ./

RUN npm install

COPY ./ ./

CMD ["node", "server.js"]

#docker run -p 호스트pc 포트 : 도커 컨테이너 포트 이미지ID
#  docker run -dp 5000:3000 -v /usr/src/app/node_modules -v $(pwd):/usr/src/app ejayjeon/nodejs
# Volumn : 이미지를 빌드하지 않아도 소스를 변동했을 때 바로 반영될 수 있게 